import "./globals.css";
import DynamicNavbar from "@/components/DynamicNavbar";
import FooterRex from "@/components/FooterRex";
import ThemeLayout from "@/components/Layout/ThemeLayout";
import SmoothScrollWrapper from "@/components/SmoothScrollWrapper"; // New Client Component

export const metadata = {
  title: "Quantafile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#010202" />
      </head>
      <body>
        <ThemeLayout>
          {/* SmoothScrollWrapper handles Lenis */}
          <SmoothScrollWrapper>
            <div className="min-h-screen dark:bg-[#010202] flex flex-col">
              <main className="flex-grow">
                <DynamicNavbar />
                {children}
                <FooterRex />
              </main>
            </div>
          </SmoothScrollWrapper>
        </ThemeLayout>
      </body>
    </html>
  );
}
